model_selection:
  model:
    RandomForestClassifier:
      search_param_grid:
        n_estimators:
          - 100
          - 200
          - 300
        max_depth:
          - None
          - 10
          - 20
          - 30
        min_samples_split:
          - 2
          - 5
          - 10
        min_samples_leaf:
          - 1
          - 2
          - 4
        bootstrap:
          - True
          - False

    XGBClassifier:
      search_param_grid:
        learning_rate:
          - 0.01
          - 0.1
          - 0.2
        n_estimators:
          - 100
          - 200
        max_depth:
          - 3
          - 5
          - 7
        subsample:
          - 0.8
          - 1
        colsample_bytree:
          - 0.8
          - 1

    SVC:
      search_param_grid:
        C:
          - 0.1
          - 1
          - 10
        kernel:
          - linear
          - rbf
        gamma:
          - scale
          - auto
        degree:
          - 3
          - 4
          - 5

    GradientBoostingClassifier:
      search_param_grid:
        n_estimators:
          - 50
          - 100
          - 200
          - 300
        learning_rate:
          - 0.01
          - 0.05
          - 0.1
          - 0.2
        max_depth:
          - 3
          - 4
          - 5
          - 6
        min_samples_split:
          - 2
          - 5
          - 10
        min_samples_leaf:
          - 1
          - 2
          - 4

    StackingClassifier:
      search_param_grid: {}  # Stacking does not have hyperparameters for grid search directly. You typically perform grid search on base learners.

    KNeighborsClassifier:
      search_param_grid:
        n_neighbors:
          - 3
          - 5
          - 7
          - 9
        weights:
          - uniform
          - distance
        metric:
          - euclidean
          - manhattan
          - minkowski
